# Generated by Django 3.0.6 on 2020-05-27 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción del curso')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('contenido_html', models.TextField(verbose_name='Contenido del curso html')),
                ('contenido_pdf', models.FileField(upload_to='./contenidos', verbose_name='Contenido del curso PDF')),
                ('num_estudiantes', models.IntegerField(verbose_name='Número de estudiantes inscritos')),
                ('curso_pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Curso', verbose_name='Curso Pre-requisito')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
