# Generated by Django 3.0.6 on 2020-05-27 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del programa')),
                ('descripcion', models.TextField(verbose_name='Descripción del programa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('snies', models.CharField(max_length=250, verbose_name='SNIES del programa')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección del programa')),
                ('email', models.CharField(max_length=250, verbose_name='Email del programa')),
                ('telefono', models.CharField(max_length=250, verbose_name='Teléfono del programa')),
                ('duracion', models.IntegerField(verbose_name='Duración')),
                ('plan_estudio', models.FileField(upload_to='./planes', verbose_name='Plan de estudio')),
                ('cordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('cursos', models.ManyToManyField(to='web.Curso', verbose_name='Cursos del programa')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Facultad', verbose_name='Facultad')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Jornada', verbose_name='Jornada')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Modalidad', verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
    ]
