# Generated by Django 3.0.6 on 2020-05-27 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('cursando', 'Cursando'), ('finalizado', 'Finalizado')], default='pendiente', max_length=32, verbose_name='Estado')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Programa', verbose_name='Programa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Programa de estudiante',
                'verbose_name_plural': 'Programas de estudiantes',
            },
        ),
        migrations.CreateModel(
            name='CursoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('cursando', 'Cursando'), ('finalizado', 'Finalizado')], default='pendiente', max_length=32, verbose_name='Estado')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Programa', verbose_name='Programa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Curso de estudiante',
                'verbose_name_plural': 'Cursos de estudiantes',
            },
        ),
    ]
