# Generated by Django 3.0.6 on 2020-05-27 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cursousuario_programausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursousuario',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programausuario',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripción'),
            preserve_default=False,
        ),
    ]
