# Generated by Django 3.0.6 on 2020-05-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200527_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del colegio')),
            ],
        ),
        migrations.CreateModel(
            name='PregradosEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del programa')),
            ],
            options={
                'verbose_name': 'Pregrado de egreso',
                'verbose_name_plural': 'Pregrados de egreso',
            },
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='descripcionn',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoIdentificacion',
            new_name='tipo_identificacion',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='programa',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='resultado_examen',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Resultado examen de admisión'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='colegio_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ColegioEgreso', verbose_name='Colegio de egreso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pregrado_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.PregradosEgreso', verbose_name='Pregrado de egreso'),
        ),
    ]
