# Generated by Django 3.0.6 on 2020-05-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200528_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='contenido_html',
        ),
    ]
