# Generated by Django 3.0.6 on 2020-05-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
