# Generated by Django 3.0.6 on 2020-05-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200528_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre del curso'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre del programa'),
        ),
    ]
