# Generated by Django 3.0.6 on 2020-05-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200529_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursousuario',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Programa', verbose_name='Programa'),
        ),
    ]
