# Generated by Django 3.0.6 on 2020-05-29 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200529_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursousuario',
            name='semestre',
            field=models.IntegerField(default=1, verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='programausuario',
            name='semestre',
            field=models.IntegerField(default=1, verbose_name='Semestre'),
        ),
        migrations.CreateModel(
            name='CursoSemestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_curso', models.IntegerField(default=1, verbose_name='Maxímo de cursos por semestre')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Curso', verbose_name='Curso')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Máximo curso por semestre',
                'verbose_name_plural': 'Maxímos cursos por semestres',
            },
        ),
    ]
