# Generated by Django 3.0.6 on 2020-05-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200529_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nota_pregrado',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nota pregrado'),
        ),
    ]
